"""add mongo document reference to analyses

Revision ID: bc188455a0a3
Revises: 4a6162aaa06c
Create Date: 2026-07-15 08:17:18.233286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc188455a0a3'
down_revision: Union[str, Sequence[str], None] = '4a6162aaa06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('mongo_document_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'mongo_document_id')
    # ### end Alembic commands ###
